/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interiormanagement.View;

import interiormanagement.Class.Employee;
import interiormanagement.ContentProvider;
import interiormanagement.Controller.ProcessDatabase;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class ChangePassFrame extends javax.swing.JFrame {
    private Employee nhanvien;
    private ProcessDatabase process; 
    /**
     * Creates new form changePassFrame
     */
    public ChangePassFrame(Employee nhanvien) {
        this.nhanvien = nhanvien;
        initComponents();
        setLocationRelativeTo(null);
        setSize(400, 350);
        setTitle("Quản lý cửa hàng nội thất DreamHouse");
        
        // set icon jframe
        ContentProvider.Logo(this);

        process = new ProcessDatabase();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        themSPTableButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        tenKHTextField = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        diachiKHTextField = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        sdtKHTextField = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        topPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        acceptButton = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        tfPassOld = new javax.swing.JPasswordField();
        jPanel22 = new javax.swing.JPanel();
        tfPassNew = new javax.swing.JPasswordField();
        jPanel23 = new javax.swing.JPanel();
        tfPassNewAgain = new javax.swing.JPasswordField();
        jPanel24 = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(250, 198));

        jPanel7.setBackground(new java.awt.Color(255, 51, 102));
        jPanel7.setPreferredSize(new java.awt.Dimension(500, 45));
        jPanel7.setLayout(new java.awt.GridLayout(1, 2));

        jLabel8.setText("Mật khẩu cũ");
        jPanel7.add(jLabel8);

        jPanel8.setPreferredSize(new java.awt.Dimension(187, 44));
        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        jLabel7.setText("Mật khẩu mới");
        jPanel8.add(jLabel7);

        jPanel9.setPreferredSize(new java.awt.Dimension(331, 44));
        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        jLabel9.setText("Nhập lại mật khẩu");
        jPanel9.add(jLabel9);

        jPanel17.setLayout(new java.awt.GridLayout(1, 0));

        themSPTableButton1.setText("Chấp Nhận");
        themSPTableButton1.setPreferredSize(new java.awt.Dimension(127, 44));
        themSPTableButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themSPTableButton1ActionPerformed(evt);
            }
        });
        jPanel17.add(themSPTableButton1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(250, 249));

        jPanel10.setBackground(new java.awt.Color(255, 51, 102));
        jPanel10.setPreferredSize(new java.awt.Dimension(500, 45));
        jPanel10.setLayout(new java.awt.GridLayout(1, 0));
        jPanel10.add(tenKHTextField);

        jPanel11.setBackground(new java.awt.Color(255, 51, 102));
        jPanel11.setPreferredSize(new java.awt.Dimension(367, 44));
        jPanel11.setLayout(new java.awt.GridLayout(1, 0));
        jPanel11.add(diachiKHTextField);

        jPanel12.setBackground(new java.awt.Color(255, 51, 102));
        jPanel12.setPreferredSize(new java.awt.Dimension(145, 44));
        jPanel12.setLayout(new java.awt.GridLayout(1, 0));

        sdtKHTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sdtKHTextFieldKeyTyped(evt);
            }
        });
        jPanel12.add(sdtKHTextField);

        jPanel19.setPreferredSize(new java.awt.Dimension(209, 44));
        jPanel19.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setText("Hủy");
        jPanel19.add(jButton1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel6);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        topPanel.setPreferredSize(new java.awt.Dimension(400, 50));
        topPanel.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setBackground(new java.awt.Color(95, 212, 197));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(47, 55, 67));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ĐỔI MẬT KHẨU");
        jLabel1.setOpaque(true);
        topPanel.add(jLabel1);

        getContentPane().add(topPanel, java.awt.BorderLayout.PAGE_START);

        centerPanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setPreferredSize(new java.awt.Dimension(250, 198));
        jPanel13.setLayout(new java.awt.GridLayout(4, 0, 0, 5));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setPreferredSize(new java.awt.Dimension(500, 45));
        jPanel14.setLayout(new java.awt.GridLayout(1, 2));

        jLabel10.setText("Mật khẩu cũ");
        jPanel14.add(jLabel10);

        jPanel13.add(jPanel14);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setPreferredSize(new java.awt.Dimension(187, 44));
        jPanel15.setLayout(new java.awt.GridLayout(1, 0));

        jLabel11.setText("Mật khẩu mới");
        jPanel15.add(jLabel11);

        jPanel13.add(jPanel15);

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setPreferredSize(new java.awt.Dimension(331, 44));
        jPanel16.setLayout(new java.awt.GridLayout(1, 0));

        jLabel12.setText("Nhập lại mật khẩu");
        jPanel16.add(jLabel12);

        jPanel13.add(jPanel16);

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setLayout(new java.awt.GridLayout(1, 0));

        acceptButton.setText("Chấp Nhận");
        acceptButton.setPreferredSize(new java.awt.Dimension(127, 44));
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });
        jPanel18.add(acceptButton);

        jPanel13.add(jPanel18);

        jPanel2.add(jPanel13);

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setPreferredSize(new java.awt.Dimension(250, 249));
        jPanel20.setLayout(new java.awt.GridLayout(4, 0, 0, 5));

        jPanel21.setPreferredSize(new java.awt.Dimension(500, 45));
        jPanel21.setLayout(new java.awt.GridLayout(1, 0));

        tfPassOld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPassOldKeyTyped(evt);
            }
        });
        jPanel21.add(tfPassOld);

        jPanel20.add(jPanel21);

        jPanel22.setPreferredSize(new java.awt.Dimension(367, 44));
        jPanel22.setLayout(new java.awt.GridLayout(1, 0));

        tfPassNew.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPassNewKeyTyped(evt);
            }
        });
        jPanel22.add(tfPassNew);

        jPanel20.add(jPanel22);

        jPanel23.setPreferredSize(new java.awt.Dimension(145, 44));
        jPanel23.setLayout(new java.awt.GridLayout(1, 0));

        tfPassNewAgain.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPassNewAgainKeyTyped(evt);
            }
        });
        jPanel23.add(tfPassNewAgain);

        jPanel20.add(jPanel23);

        jPanel24.setPreferredSize(new java.awt.Dimension(209, 44));
        jPanel24.setLayout(new java.awt.GridLayout(1, 0));

        cancelButton.setText("Hủy");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel24.add(cancelButton);

        jPanel20.add(jPanel24);

        jPanel2.add(jPanel20);

        javax.swing.GroupLayout centerPanelLayout = new javax.swing.GroupLayout(centerPanel);
        centerPanel.setLayout(centerPanelLayout);
        centerPanelLayout.setHorizontalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                .addContainerGap())
        );
        centerPanelLayout.setVerticalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void themSPTableButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themSPTableButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_themSPTableButton1ActionPerformed

    private void sdtKHTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sdtKHTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_sdtKHTextFieldKeyTyped

    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
        if (validateInfo()) {
            JOptionPane.showMessageDialog(centerPanel,"Bạn chưa nhập đủ thông tin!");
        }else{
          if (tfPassOld.getText().equals(nhanvien.getPass())) {
            if (tfPassNew.getText().equals(tfPassNewAgain.getText())) {
                if (ChangePassword()) {
                    JOptionPane.showMessageDialog(centerPanel,"Đổi mật khẩu thành công!");
                    setVisible(false);
                }else
                    JOptionPane.showMessageDialog(centerPanel,"Đổi mật khẩu thất bại!");
                
                process.CloseConnect();
            }else
                JOptionPane.showMessageDialog(centerPanel,"Mật khẩu nhập lại không trùng khớp !");
        }else
            JOptionPane.showMessageDialog(centerPanel,"Mật khẩu cũ sai!");
        }
    }//GEN-LAST:event_acceptButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void tfPassOldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPassOldKeyTyped
         if(tfPassOld.getText().length() > 50)
            evt.consume();
    }//GEN-LAST:event_tfPassOldKeyTyped

    private void tfPassNewKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPassNewKeyTyped
       if(tfPassNew.getText().length() > 50)
            evt.consume();
    }//GEN-LAST:event_tfPassNewKeyTyped

    private void tfPassNewAgainKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPassNewAgainKeyTyped
        if(tfPassNewAgain.getText().length() > 50)
            evt.consume();
    }//GEN-LAST:event_tfPassNewAgainKeyTyped

    private boolean ChangePassword(){
        if (process.Connect()) {
            return process.ChangePassword(nhanvien.getIdEmployee(), tfPassNew.getText());
        }
        return false;
    }
    
    private boolean validateInfo(){
        if (tfPassOld.getText().equals("") || tfPassNew.getText().equals("") || tfPassNewAgain.getText().equals("")) {
            return true;
        }
        return false;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ChangePassFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JTextField diachiKHTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField sdtKHTextField;
    private javax.swing.JTextField tenKHTextField;
    private javax.swing.JPasswordField tfPassNew;
    private javax.swing.JPasswordField tfPassNewAgain;
    private javax.swing.JPasswordField tfPassOld;
    private javax.swing.JButton themSPTableButton1;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
