/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interiormanagement.View;

import interiormanagement.Class.TypeProduct;
import interiormanagement.ContentProvider;
import interiormanagement.Controller.ProcessDatabase;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class TypeProductFrame extends javax.swing.JFrame {
    String[] titles = {"STT","Tên Loại"};
     private DefaultTableModel model;
     private ProcessDatabase process;
     private ResultSet resultSet;
     private ArrayList<TypeProduct> typeProducts; 
    /**
     * Creates new form TypeProductFrame
     */
    public TypeProductFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Quản lý cửa hàng nội thất DreamHouse");
        
        // set icon jframe
        ContentProvider.Logo(this);
        
        process = ContentProvider.process;
        
        model = (DefaultTableModel) typeProductTable.getModel();
        model.setColumnIdentifiers(titles);

        typeProducts = new ArrayList<>();
        
        setButtonEnable(false, false);
        
        ShowDataTable();
        typeProductTable.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (typeProductTable.getSelectedRow() > -1) {
                     tfTypeName.setText(typeProducts.get(typeProductTable.getSelectedRow()).getTenLoai());
                setButtonEnable(true, true);
                }
            }
        });
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfTypeName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        typeProductTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        topPanel.setPreferredSize(new java.awt.Dimension(400, 70));
        topPanel.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setBackground(new java.awt.Color(95, 212, 197));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOẠI SẢN PHẨM");
        jLabel1.setOpaque(true);
        topPanel.add(jLabel1);

        getContentPane().add(topPanel, java.awt.BorderLayout.PAGE_START);

        centerPanel.setBackground(new java.awt.Color(255, 255, 255));
        centerPanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 50));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        addButton.setText("Thêm");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addButton);

        updateButton.setText("Sửa");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(updateButton);

        deleteButton.setText("Xóa");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(deleteButton);

        exitButton.setText("Thoát");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(exitButton);

        centerPanel.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tên Loại");
        jPanel3.add(jLabel2);

        tfTypeName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfTypeNameKeyTyped(evt);
            }
        });
        jPanel3.add(tfTypeName);

        typeProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(typeProductTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
        );

        centerPanel.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
       boolean check = false;
        for (TypeProduct type : typeProducts) {
            if (tfTypeName.getText().toLowerCase().equals(type.getTenLoai().toLowerCase())) {
                check = true;
            }
        }
        if (!check) {
            if (InsertType()) {
            JOptionPane.showMessageDialog(centerPanel, "Thêm Thành Công!");
            tfTypeName.setText("");
            ShowDataTable();
            }else
                JOptionPane.showMessageDialog(centerPanel, "Thêm Thất Bại!");
        }else
            JOptionPane.showMessageDialog(centerPanel,"Loại Sản Phẩm đã tồn tại!");
       

    }//GEN-LAST:event_addButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        boolean check = false;
        for (TypeProduct type : typeProducts) {
            if (tfTypeName.getText().toLowerCase().equals(type.getTenLoai().toLowerCase())) {
                check = true;
            }
        } 
        if (UpdateType() && !check) {
            JOptionPane.showMessageDialog(centerPanel, "Sửa Thành Công!");
            tfTypeName.setText("");
            ShowDataTable();
            setButtonEnable(false, false);
         }else
            JOptionPane.showMessageDialog(centerPanel, "Sửa Thất Bại!");
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int result = JOptionPane.showConfirmDialog(centerPanel, "Bạn có chắc muốn xóa không?","Thông báo",JOptionPane.YES_NO_OPTION);
        if (result == 0) {
            if (DeleteType()) {
            ShowDataTable();
            setButtonEnable(false, false);
            tfTypeName.setText("");
        }else
            JOptionPane.showMessageDialog(centerPanel, "Loại này còn tồn tại trong kho !");
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void tfTypeNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTypeNameKeyTyped
        char c = evt.getKeyChar();
        if(tfTypeName.getText().length() > 90)
            evt.consume();
    }//GEN-LAST:event_tfTypeNameKeyTyped
  
    private void setButtonEnable(boolean update,boolean delete){
        updateButton.setEnabled(update);
        deleteButton.setEnabled(delete);
    }
    private void ShowDataTable(){
        model.setRowCount(0);
        typeProducts.clear();
        resultSet = ContentProvider.getList(TypeProduct.TABLE_NAME);

        try {
            while(resultSet.next()){
                typeProducts.add(new TypeProduct(resultSet.getInt("MALOAI"), resultSet.getNString("TENLOAI")));
            }
        } catch (SQLException ex) {
            Logger.getLogger(TypeProductFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        AddRow();
        process.CloseConnect();
    }
    
    private void AddRow(){
        int stt = 1;
        for(TypeProduct type : typeProducts){
            model.addRow(new Object[]{
                stt,
                type.getTenLoai()
            });
            stt++;
        }
    }
    
    private boolean InsertType(){
        if (process.Connect()) {
           return process.InsertType(tfTypeName.getText());
        }
        return false;
    }
    
    private boolean UpdateType(){
     if (process.Connect()) {
           return process.UpdateType(typeProducts.get(typeProductTable.getSelectedRow()).getMaLoai(),tfTypeName.getText());
        }
        return false;
    }
    
    private boolean DeleteType(){
        if (process.Connect()) {
           return process.DeleteData(TypeProduct.TABLE_NAME,"MALOAI",String.valueOf(typeProducts.get(typeProductTable.getSelectedRow()).getMaLoai()));
        }
        return false;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TypeProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TypeProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TypeProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TypeProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TypeProductFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfTypeName;
    private javax.swing.JPanel topPanel;
    private javax.swing.JTable typeProductTable;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
